variable "bcp_lab_org_projects" {
  default = {
    enable            = true
    organization_name = "bcp-lab-org"
    description       = "Organization generated by terraform harness provider"
    projects = {
      "Development iOS Team" = {
        enable      = true
        description = "Project generated by terraform harness provider"
      }
    }
  }
}
