locals {
  bcp_secrets_org = {
    platform_api_key = {
      secret      = data.harness_platform_secret_text.harness_secrets["platform_api_key_1"].value
      org_id      = module.bootstrap_harness.organization[var.bcp_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
    platform_account_id = {
      secret      = data.harness_platform_secret_text.harness_secrets["platform_account_id_1"].value
      org_id      = module.bootstrap_harness.organization[var.bcp_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
    connector_bcp_github_token = {
      secret      = data.harness_platform_secret_text.harness_secrets["connector_crizstian_github_token_1"].value
      org_id      = module.bootstrap_harness.organization[var.bcp_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
    connector_bcp_docker_token = {
      secret      = data.harness_platform_secret_text.harness_secrets["connector_crizstian_docker_token_1"].value
      org_id      = module.bootstrap_harness.organization[var.bcp_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
    connector_bcp_artifactory_token = {
      secret      = data.harness_platform_secret_text.harness_secrets["connector_crizstian_artifactory_token_1"].value
      org_id      = module.bootstrap_harness.organization[var.bcp_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
  }
}
